export const industryOptions = [
  { value: "Technology", label: "Technology" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Finance", label: "Finance" },
  { value: "E-commerce", label: "E-commerce" },
  { value: "Food and Beverage", label: "Food and Beverage" },
  { value: "Education", label: "Education" },
  { value: "Entertainment", label: "Entertainment" },
  { value: "Renewable Energy", label: "Renewable Energy" },
  { value: "Transportation", label: "Transportation" },
  { value: "Fashion and Apparel", label: "Fashion and Apparel" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Travel and Hospitality", label: "Travel and Hospitality" },
  { value: "Automotive", label: "Automotive" },
  { value: "Agriculture", label: "Agriculture" },
  { value: "Marketing and Advertising", label: "Marketing and Advertising" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Construction", label: "Construction" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Environmental Services", label: "Environmental Services" },
  { value: "Fitness and Wellness", label: "Fitness and Wellness" },
];

export const sizeOptions = [
  { value: "1-5 employees", label: "1-5 employees" },
  { value: "5-10 employees", label: "5-10 employees" },
  { value: "10-50 employees", label: "10-50 employees" },
  { value: "50-100 employees", label: "50-100 employees" },
  { value: "101-150 employees", label: "101-150 employees" },
  { value: "151-200 employees", label: "151-200 employees" },
  { value: "201-250 employees", label: "201-250 employees" },
  { value: "251-300 employees", label: "251-300 employees" },
  { value: "301-350 employees", label: "301-350 employees" },
  { value: "351-400 employees", label: "351-400 employees" },
  { value: "401-450 employees", label: "401-450 employees" },
  { value: "451-500 employees", label: "451-500 employees" },
  { value: "500+ employees", label: "500+ employees" },
];
